<?php

/**
 * @package     Optimiseweb_Getclicky
 * @author      Kathir Vel (sid@optimiseweb.co.uk)
 * @copyright   Copyright (c) 2013 Optimise Web Limited
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$getClickyGoalEnabled = Mage::getStoreConfig('optimisewebgetclickyconfig/goal_cart_page/enabled');
$getClickyGoalType = Mage::getStoreConfig('optimisewebgetclickyconfig/goal_cart_page/goal_type');
if (Mage::getStoreConfig('optimisewebgetclickyconfig/goal_cart_page/goal_name')) {
    $getClickyGoalName = Mage::getStoreConfig('optimisewebgetclickyconfig/goal_cart_page/goal_name');
} else {
    $getClickyGoalName = 'Cart Page';
}
if (Mage::getStoreConfig('optimisewebgetclickyconfig/goal_cart_page/goal_id')) {
    $getClickyGoalId = Mage::getStoreConfig('optimisewebgetclickyconfig/goal_cart_page/goal_id');
} else {
    $getClickyGoalType = 'dynamic';
}

$js = "";
$js .= "<script type=\"text/javascript\">\n";
$js .= "var clicky_custom = clicky_custom || {};\n";
$js .= "clicky_custom.goal = {\n";
if ($getClickyGoalType == 'dynamic') {
    $js .= "name: \"" . $getClickyGoalName . "\"\n";
} else {
    $js .= "id: \"" . $getClickyGoalId . "\"\n";
}
$js .= "};\n";
$js .= "</script>\n";

echo $js;